version: "3"

networks:
  net:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.40.0.0/16

services:
  # NextJS Application running frontend of the Price Bandit
  # frontend:
  #   container_name: frontend
  #   # restart: unless-stopped
  #   networks:
  #     - net
  #   build:
  #     context: ./frontend
  #   environment:
  #     - TZ=${TZ}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #     - timescaledb

  # FastAPI Application that runs API for scraper and website
  backend:
    container_name: backend
    # restart: unless-stopped
    networks:
      - net
    build:
      context: ./backend
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - POSTGRES_URL=${POSTGRES_URL}
      - EXPIRE_DELTA=${EXPIRE_DELTA}
    ports:
      - "5000:5000"
    depends_on:
      - scraper
      - timescaledb
      - redis

  # Scrapper tool for the backend
  scraper:
    container_name: scraper
    # restart: unless-stopped
    networks:
      - net
    build:
      context: ./scraper
    environment:
      - TZ=${TZ}

  # TimescaleDB container
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    # restart: unless-stopped
    networks:
      - net
    environment:
      - TIMESCALEDB_TELEMETRY=off
      - PUID=${TSDB_ID}
      - PGID=${TSDB_ID}
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/timescaledb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    depends_on:
      - scraper

  # Redis container
  redis:
    image: redis:latest
    container_name: redis
    # restart: unless-stopped
    networks:
      - net
    ports:
      - "6379:6379"
    volumes:
      - ${VOLUMES_PATH}/redis/:/bitnami
    depends_on:
      - scraper
      - timescaledb
